---
project_name: patterns-go
loglevel: info
analyses:
  - analysis_name: golang check
    source_directory: ABSOLUTE_PATH_TO_EXPORT_DIRECTORY
    only_permit_languages:
      - go
    only_permit_file_extensions:
      - .go
    file_scan:
      - number_of_methods
      - source_lines_of_code
      - dependency_graph
      - louvain_modularity
      - fan_in_out
      - git_metrics
    export:
      - directory: ABSOLUTE_PATH_TO_EXPORT_DIRECTORY
      - graphml
      - json
      - tabular_file
      - tabular_console_overall
      - d3
    git_directory: ABSOLUTE_PATH_TO_EXPORT_DIRECTORY/.git
    git_commit_limit: 100
    git_exclude_merge_commits: true